### ISSUE TITLE
Add parameter metadata switch to copy another parameter at a cadence

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-core#158]
For example, if we have in the metadata for a parameter:

```yaml
benefits_level:
  2010-01-01: 100
metadata:
  uprating: 
    parameter: gov.inflation
    as_of: october last year
```
