### ISSUE TITLE
`threshold_variable` metadata field specifying the variable that parameter scale thresholds are based on

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#83]
To enable this:
```yaml
description: NYC provides a household credit of this fixed amount to single filers, based on recomputed federal AGI.
metadata:
  label: NYC Household Credit Fixed Amount for single filers
  type: single_amount
  threshold_unit: currency-USD
  amount_unit: currency-USD
  threshold_variable: adjusted_gross_income # PROPOSAL
  reference:
    - title: Instructions for Form IT-201
      href: https://www.tax.ny.gov/pdf/2022/printable-pdfs/inc/it201i-2022.pdf#page=17
values:
  - threshold:
      2022-01-01: 10_000
    amount:
      2022-01-01: 15
  - threshold:
      2022-01-01: 12_500
    amount:
      2022-01-01: 10
  - threshold:
      2022-01-01: 12_501
    amount:
      2022-01-01: 0
```

cc @leogoldman
